name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Print info
      run: |
        uname -a
        pwd
        env
        ls -a
    - name: Set up the environment
      run: |
        pip install Cython nimporter
        wget --quiet https://nim-lang.org/download/nim-1.0.4-linux_x64.tar.xz
        tar -xf nim-1.0.4-linux_x64.tar.xz
        export PATH="$GITHUB_WORKSPACE/nim-1.0.4/bin:$PATH"
        ./nim-1.0.4/bin/nimble install --accept nimpy
    - name: Run the performance test script
      run: |
        python main.py
